version: '3.8'

services:
  server:
    build: .
    image: server
    command: npm start
    ports:
      - 3000:8080

  cipherjokes-tests:
    image: server
    command: dockerize
        -wait tcp://server:8080 -timeout 10s
        bash -c "npm test"
    environment:
      APP_URL: http://localhost:3000
    depends_on:
      - server